const JOIN_ROOM = "JOIN_ROOM";
const CONNECTION_ACK = "CONNECTION_ACK";
const LEAVE_ROOM = "LEAVE_ROOM";
const SEND_MSG = "SEND_MSG";
const RCV_MSG = "RCV_MSG";

module.exports = { JOIN_ROOM, CONNECTION_ACK, LEAVE_ROOM, SEND_MSG, RCV_MSG };
