const JOIN_ROOM = "JOIN_ROOM";
const CONNECTION_ACK = "CONNECTION_ACK";
const LEAVE_ROOM = "LEAVE_ROOM";
const SEND_MSG = "SEND_MSG";
const RCV_MSG = "RCV_MSG";
const LEFT_ROOM = "LEFT_ROOM";
const CONNECT_CALL = "CONNECT_CALL";

module.exports = {
  JOIN_ROOM,
  CONNECTION_ACK,
  LEAVE_ROOM,
  SEND_MSG,
  RCV_MSG,
  LEFT_ROOM,
  CONNECT_CALL,
};
